config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get 'users/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # get '/login/microposts', to: 'microposts#new'

  resources :users
  resources :microposts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 440 }
  validates :published_on, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence:true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 230 },
             uniqueness: true
  # validates :password, presence: true, length: { maximum: 430 },\
  # :on => :update, :unless => lambda { |user| user.password.blank? }
  validates :password_digest, presence: true,\
  if: ->(user) { user.password_digest_changed? }

  validates :avatar, presence: true,\
  if: ->(user) { user.password_digest_changed? }

  has_secure_password
  has_one_attached :avatar

  # check with dependent: :destroy in case of avatar(2nd demo)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  rescue_from ActionController::InvalidAuthenticityToken do
    # @exception = exception.message
    render 'shared/500', :status => 200
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i[create edit destroy update index show]
  # before_action :chk_access, only: %i[ edit update destroy show ]
  before_action :chk_access, only: %i[ index ]

  # GET /microposts or /microposts.json
  def index
    @microposts = current_user.microposts
  end

  # GET /microposts/1 or /microposts/1.json
  def show
    @micropost =  Micropost.find(params[:id])
    # @micropost.content
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new
    @micropost = current_user.microposts.build(micropost_params) if logged_in?

    @micropost.save
    # # respond_to do |format|

    #   if @micropost.nil? && @micropost.save
    #     format.js
    #   else
    #     #redirect_to new_micropost_url
    #   end
    # end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])
    @micropost.update_columns(content: micropost_params[:content], published_on: \
                              micropost_params[:published_on])
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    flash[:success] = "Micropost was successfully destroyed."
    redirect_to microposts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:id, :user_id, :content, :published_on)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
      #  @micropost = Micropost.find(params[:id])
    end

    def chk_access
      # @micropost = Micropost.find(params[:id])
      @microposts = current_user.microposts
      if @microposts.first.user_id != current_user.id
        flash[:danger] = "Authoriztion failed"
        redirect_to shared/error_authorization
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)

    if user && user.authenticate(params[:password])
      log_in user
      flash[:success] = "Hii #{user[:name]} successfully logged in.Session started"
      redirect_to user_path(user.id)
    else
      flash[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    flash[:success] = "Bye successfully logged out.Session ended"
    session.destroy
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # => @micropost = current_user.microposts.build if logged_in?
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[ show edit update ]
  before_action :chk_access, only: %i[ show edit update ]
  before_action :set_user, only: :destroy
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(session[:user_id])
  end

  # GET /users/new
  def new
    @user = User.new

  end

  # GET /users/13/edit
  def edit
  end

  # remove avatar attach (pic upload) from sign up page(2nd demo)

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.avatar.attach(user_params[:avatar])

    if @user.save
      flash[:success] = "Sign Up Process Successfull.Welcome #{@user[:name]} to the QI Blog.Please Login to Continue"
      redirect_to user_path current_user
    else
      flash[:danger] = "Oops something went wrong"
      render 'new'
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update

    @user.avatar.attach(user_params[:avatar])

    if @user.update_columns(name: user_params[:name])
      flash[:success] = "User was successfully updated."
      redirect_to user_path(@current_user)
    else
      flash[:danger] = "Sorry Something went wrong"
      redirect_to login_url
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if @user.avatar.destroy
        flash[:success] = "Profile picture successfully removed."
    else
        flash[:danger] = "Oops smething went wrong"
    end
    redirect_to user_path current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      if !params.nil?
        params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :avatar)
      end
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
      @user = User.find(params[:id])
    end

    def chk_access
      if @user.id != current_user.id
        flash[:danger] = "Authoriztion failed"
        render 'shared/error_authorization'
      end
    end

    def delete_avatar

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    session[:user_email] = user.email
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_micropost_user_id
    @current_micropost_user_id ||= Micropost.find_by(user_id: session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
 end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    All Rights reserved by QI
  </small>

  <nav>
    <%= link_to "Help", '#' %>
    <%= link_to "Home", root_path %>

    <% if logged_in? %>
      <%= link_to "Log out", logout_path, method: "delete" %>
    <% else %>
      <%= link_to "Log in", login_path %>
    <% end%>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<title> QI Blog </title>

<nav class="navbar navbar-expand-lg navbar-dark bg-success">

  <div class="container-fluid">

    <% if logged_in?%>
      <%= link_to "Log out", logout_path, class: "navbar-brand", method: "delete" %>
    <% else %>
      <%= link_to "Log in", login_path, class: "navbar-brand" %>
    <% end%>

    <form class="d-flex">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title) %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">

          <% flash.each do |message_type, message| %>
            <div class="alert-fixed alert-<%=message_type%> centre"><%=message%></div>
          <%end %>
          <%= yield %>
        </div>
      </div>
    </div>

  <% render 'layouts/footer' %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= provide(:title, 'Activity-Page') %>
<%= form_with(model: item, local: false) do |form| %>
  <section>
    <div>
      <div>
        <div>
          <%= form.label :content %>
          <%= form.text_area :content %>
          <%= form.text_field :published_on, class: 'flatpickr', required: true %>
          <input type="hidden" name="id" value=<%=session[:user_id]%>><br>

          <div class="actions">
             &nbsp;&nbsp;<%= form.submit "Create my Blog" %>
             <%= link_to 'Back', microposts_path, class: 'btn btn-secondary'%>
          </div>

        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/microposts/_micropost.html.erb
<tr id="blog-edit-<%=micropost.id %>">

  <td>
    <%= micropost.content %>
  </td>
  <td>
    <%= micropost.published_on %>
  </td>
  <td>
    <%= link_to 'Show', micropost, remote: true %>
    <%= link_to 'Edit', edit_micropost_path(micropost), method: :get, remote: true %>
    <%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/microposts/create.js.erb
alert("Hurray Blog is created....");
$("#blog-list").append("<%= j render 'micropost', micropost: @micropost %>");

app/views/microposts/edit.html.erb
<h1>Editing Microposts</h1>

<%= render 'form', micropost: @micropost %>
<%= link_to 'Show', @micropost %>
<%= link_to 'Back', microposts_path %>

app/views/microposts/edit.js.erb
alert("Hii please proceed to edit your blog..");
$("#blogs").append("<%= j render 'form', item: @micropost %>");
flatpickr('.flatpickr',{ enableTime: true, dateFormat: "Y-m-d H:i" });

app/views/microposts/index.html.erb
<%= provide(:title, 'Activity-Page') %>
<%= link_to 'Back', user_path(current_user), class: 'btn btn-secondary'%>
<%= link_to 'Add New Blog', new_micropost_path, method: :get, remote: true %>

<h3>Blogs for <%=session[:user_email]%></h3>
  <table class="center" id="blog-list">

    <% @microposts.each do |micropost| %>
      <%= render 'micropost', micropost: micropost %>
    <% end %>
  </table>

<div id="blogs">
</div>

app/views/microposts/micropost.html.erb
<li id="micropost-<%= micropost.id %>">
<%= link_to gravatar_for(micropost.user) %>
<span class="user"><%= link_to micropost.user.name,micropost.user %></span>
<span class="content"><%= micropost.content %></span>
  
<span class="timestamp">
  Posted <%= time_ago_in_words(micropost.created_at) %> ago.
</span>
</li>

app/views/microposts/new.html.erb
<% provide(:title, 'Activity-Page') %>
<h4>New Micropost for <%session[:user_email]%></h4>
<%render 'form', micropost: @micropost %>

app/views/microposts/new.js.erb
$(document).ready(function(){
  alert("Hii please proceed..");
  $("#blogs").append("<%= j render 'form', item: @micropost %>");
  flatpickr('.flatpickr',{ enableTime: true, dateFormat: "Y-m-d H:i" })
})

app/views/microposts/show.js.erb
$.ajax({ success: function(result){
  alert("Hello The blog is\n<%=@micropost.content%>");}
});

app/views/microposts/update.js.erb
alert("Hurray Blog has been successfully edited....");
$("#blog-edit-<%=@micropost.id %>").replaceWith("<%= j render 'micropost', micropost: @micropost %>");

app/views/shared/500.html.erb
<h1>Oop's Error.Someone has tapped your request.</h1>

app/views/shared/_error_messeges.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">

    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>

    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new
    micropost..." %>
  </div>

  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/error_authorization.html.erb
<h1>Permission Denied</h1>

app/views/static_pages/help.html.erb
<!-- Page Content -->
<section class="py-5">
  <div class="container">
    <h1 class="fw-light">Full Page Image Slider</h1>
    <p class="lead">The background images for the slider are set directly in the HTML using inline CSS. The images
      in this snippet are from </p>
  </div>
</section>

app/views/static_pages/home.html.erb
<%= link_to 'Sign Up Now', '/signup', class: 'btn btn-lg btn-primary text-center' %>

app/views/users/_display_micropost.html.erb
<li>
  <span class="user"><%= link_to micropost.user.name,
  micropost.user %></span>

  <span class="content"><%= micropost.content %></span>
  
  <span class="timestamp">
  
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/users/_error.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
      <% @user.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>

    <div >
      <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:

      <ul class="error_explanation">
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div id="non-editable" class="field">
    <%= form.label :email %>
    <%= form.email_field :email%>
  </div>

  <div>
    <%= form.label :"Upload Profile Photo" %>
    <%= form.file_field :avatar %>
  </div>

  <div>
    <% if user.avatar.attached? %>
      <%= link_to "Delete Profile ID", user, method: :delete, data: { confirm: 'Are you sure to delete your profile picture?' } %>
    <%end%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/create.js.erb
alert("hii");

app/views/users/edit.html.erb
<%= provide(:title, session[:user_email]+'-Edit-Page') %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<%= link_to 'Back', user_path(current_user) %>

app/views/users/index.html.erb
Users
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>UserName</th>
      <th>UserEmail</th>
      <th>UserCreated Time</th>
      <th>UserUpdated Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Sign Up', new_user_path %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
  <%= form_with(model: @user) do |f| %>
    <section>
      <div class="card" style="background-color: yellow ;border-radius: 2px; height: 4%">

        <div class="container">
          <table>
            <tr>
              <td><%= f.label :name %></td>
              <td><%= f.text_field :name %></td>
            </tr>

            <tr>
              <td><%= f.label :email %></td>
              <td><%= f.email_field :email %></td>
            </tr>

            <tr>
              <td><%= f.label :password %></td>
              <td><%= f.password_field :password %></td>
            </tr>

            <tr>
              <td><%= f.label :password_confirmation, "Confirmation"%></td>
              <td><%= f.password_field :password_confirmation %></td>
            </tr>

            <div class="actions">
              <%= f.submit "Create my account" %>
              <%= link_to 'Back', root_path ,class: 'btn-secondary'%>
            </div>
          </table>
        </div>
      </div>
    </section>
  <% end %>

app/views/users/show.html.erb
<%= provide(:title, "HomePage") %>
<div class="flex-item">

  <%= form_with(model: @user) do |f| %>
  <table class="table">

    <thead>
      <tr>
        <th class="table-info">Photo</th>
        <th class="table-info">UserName</th>
        <th class="table-info">UserEmail</th>
        <th class="table-info">UserCreated Time</th>
        <th class="table-info">UserUpdated Time</th>
        <th colspan="3" class="table-primary">Actions</th>
      </tr>
    </thead>

    <tbody>

      <tr>
          <td class="table-danger">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, style: 'width:22%;'%>
            <%else%>
              <%= gravatar_for(@user)%>
            <%end%>
          </td>

          <td class="table-danger"><%= @user.name %></td>
          <td class="table-danger"><%= @user.email %></td>
          <td class="table-danger"><%= @user.created_at %></td>
          <td class="table-danger"><%= @user.updated_at %></td>
          <td class="table-secondary"><%= link_to 'User Profile', edit_user_path %></td>
          <td class="table-secondary"><%= link_to 'Blogs', microposts_path %></td>
        </tr>
    </tbody>
   </table>
 <% end%>
 </div>